"""add shield_url to teams and make category nullable

Revision ID: 0bd038112eff
Revises: 33d5173dfd78
Create Date: 2026-03-29 18:30:28.448156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bd038112eff'
down_revision: Union[str, None] = '33d5173dfd78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('shield_url', sa.String(length=500), nullable=True))
    op.alter_column('teams', 'category',
               existing_type=mysql.ENUM('sub_10', 'sub_12', 'sub_14', 'sub_16', 'sub_18', 'senior'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'category',
               existing_type=mysql.ENUM('sub_10', 'sub_12', 'sub_14', 'sub_16', 'sub_18', 'senior'),
               nullable=False)
    op.drop_column('teams', 'shield_url')
    # ### end Alembic commands ###
