"""add penalty fields to matches

Revision ID: 1a17c878f228
Revises: 4629378bb5db
Create Date: 2026-03-29 22:42:57.793583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a17c878f228'
down_revision: Union[str, None] = '4629378bb5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_penalty', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('away_penalty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'away_penalty')
    op.drop_column('matches', 'home_penalty')
    # ### end Alembic commands ###
