"""add_email_address_gender_to_player

Revision ID: 33d5173dfd78
Revises: e6e12c6837ef
Create Date: 2026-03-24 14:42:37.869738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d5173dfd78'
down_revision: Union[str, None] = 'e6e12c6837ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('players', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('players', sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'gender')
    op.drop_column('players', 'address')
    op.drop_column('players', 'email')
    # ### end Alembic commands ###
