"""descripcion_del_cambio

Revision ID: 34b45ea71b8f
Revises: dabdfeecabea
Create Date: 2026-05-11 18:43:21.344047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b45ea71b8f'
down_revision: Union[str, None] = 'dabdfeecabea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
