"""add leg column to matches

Revision ID: 4629378bb5db
Revises: 0cca915f0858
Create Date: 2026-03-29 21:32:05.475162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4629378bb5db'
down_revision: Union[str, None] = '0cca915f0858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('leg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'leg')
    # ### end Alembic commands ###
