"""add jersey_number to match_player_stats

Revision ID: 9a0e9ea8f186
Revises: eaa2880b3e4f
Create Date: 2026-06-22 22:58:38.113088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0e9ea8f186'
down_revision: Union[str, None] = 'eaa2880b3e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_player_stats', sa.Column('jersey_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_player_stats', 'jersey_number')
    # ### end Alembic commands ###
