"""Adicionar la parte de tts para proximos partidos

Revision ID: a6b1374c7a67
Revises: fefc36503808
Create Date: 2026-06-03 21:25:04.316157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b1374c7a67'
down_revision: Union[str, None] = 'fefc36503808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
