"""add final_legs and third_place_legs

Revision ID: dabdfeecabea
Revises: 1a17c878f228
Create Date: 2026-03-29 23:02:12.693358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabdfeecabea'
down_revision: Union[str, None] = '1a17c878f228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_templates', sa.Column('final_legs', sa.Integer(), nullable=True))
    op.add_column('tournament_templates', sa.Column('third_place_legs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_templates', 'third_place_legs')
    op.drop_column('tournament_templates', 'final_legs')
    # ### end Alembic commands ###
