"""add_phone_to_player

Revision ID: dbaefc2c05e2
Revises: 38cd792e3481
Create Date: 2026-03-13 06:12:37.412855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaefc2c05e2'
down_revision: Union[str, None] = '38cd792e3481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'phone')
    # ### end Alembic commands ###
