"""add_voice_fields_to_users

Revision ID: e26ad5f1bccf
Revises: 9a0e9ea8f186
Create Date: 2026-07-09 02:53:17.059894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26ad5f1bccf'
down_revision: Union[str, None] = '9a0e9ea8f186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('azure_voice_profile_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('voice_embedding', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('voice_enrolled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'voice_enrolled_at')
    op.drop_column('users', 'voice_embedding')
    op.drop_column('users', 'azure_voice_profile_id')
    # ### end Alembic commands ###
