"""add_score_and_status_to_matches

Revision ID: e68386c3de6e
Revises: ddda81eea18c
Create Date: 2026-03-24 03:12:44.309302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68386c3de6e'
down_revision: Union[str, None] = 'ddda81eea18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('away_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('status', sa.Enum('pending', 'played', name='matchstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'away_score')
    op.drop_column('matches', 'home_score')
    # ### end Alembic commands ###
